[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.2"
hex = "0.4.3"
rand = "0.8.5"
urlencoding = "2.1.2"

[dev-dependencies]
openssl = { version = "0.10" }
proptest = "1.2.0"
criterion = "0.5.1"

[[bench]]
name = "aes_128"
harness = false
